# -*- coding: utf-8 -*-
"""Draw the pointer the machine uses, and emit it as CSS.

    python tools/make_cursor.py           print the rule
    python tools/make_cursor.py --write   write src/shell/cursor.css

Oran's ruling: the circle and dot belong to the three scrolling pages; inside the machine the
pointer is the machine's own. So the shell hides the circle and dot — that is in the entry gate
already — and this puts a 1-bit arrow in their place.

DRAWN, NOT COPIED. Apple's arrow is Apple's, exactly as Chicago and Geneva and the Apple mark
are, and the whole kit has been built to carry no licence question at all. This is the same
idiom — a black keyline around a white body, on a 16x16 grid, hotspot at the tip — and it is
ours. It reads as the machine's pointer without being anyone's property.

The grid is written out as characters so it can be read and corrected by eye:
    K black   W white   .  transparent
"""
import io
import os
import sys

sys.stdout.reconfigure(encoding='utf-8', errors='replace')
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(os.path.dirname(HERE), 'src', 'shell', 'cursor.css')

ARROW = [
    "K...............",
    "KK..............",
    "KWK.............",
    "KWWK............",
    "KWWWK...........",
    "KWWWWK..........",
    "KWWWWWK.........",
    "KWWWWWWK........",
    "KWWWWWWWK.......",
    "KWWWWWWWWK......",
    "KWWWWWKKKKK.....",
    "KWWKWWK.........",
    "KWK.KWWK........",
    "KK..KWWK........",
    "K....KWWK.......",
    ".....KWWK.......",
]

# the I-beam the machine used over text, same idiom
BEAM = [
    "..KKK...KKK.....",
    "....KWWWK.......",
    ".....KWK........",
    ".....KWK........",
    ".....KWK........",
    ".....KWK........",
    ".....KWK........",
    ".....KWK........",
    ".....KWK........",
    ".....KWK........",
    ".....KWK........",
    ".....KWK........",
    ".....KWK........",
    ".....KWK........",
    "....KWWWK.......",
    "..KKK...KKK.....",
]


def svg(grid):
    """One <rect> per run of like pixels — fewer nodes than one per pixel, same picture."""
    parts = []
    for y, row in enumerate(grid):
        x = 0
        while x < len(row):
            ch = row[x]
            n = 1
            while x + n < len(row) and row[x + n] == ch:
                n += 1
            if ch in 'KW':
                parts.append('<rect x="%d" y="%d" width="%d" height="1" fill="%s"/>'
                             % (x, y, n, '#000' if ch == 'K' else '#fff'))
            x += n
    return ('<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" '
            'shape-rendering="crispEdges">' + ''.join(parts) + '</svg>')


def uri(grid):
    import urllib.parse
    return "url(\"data:image/svg+xml,%s\")" % urllib.parse.quote(svg(grid), safe="")


def main():
    css = (
        "/* THE MACHINE'S OWN POINTER.\n"
        "   Generated by tools/make_cursor.py — edit the grid there, not this file.\n"
        "   Drawn rather than copied: Apple's arrow is Apple's, like Chicago and the Apple mark,\n"
        "   and the kit carries no licence question anywhere. Same idiom, ours.\n"
        "   The hotspot is the tip, 1 1, which is where a Macintosh put it. */\n"
        "html.mw-on, html.mw-on .mw, html.mw-on .mw *{cursor:%s 1 1, default}\n"
        "html.mw-on .mw-icon, html.mw-on .mw-x, html.mw-on .mw-done,\n"
        "html.mw-on #c-folder, html.mw-on .lampband, html.mw-on .sf-tab,\n"
        "html.mw-on button, html.mw-on a{cursor:%s 1 1, pointer}\n"
        "/* over running text the machine showed a beam, and so does this */\n"
        "html.mw-on .mw-view p, html.mw-on .mw-view .para,\n"
        "html.mw-on .mw-view .lead, html.mw-on .mw-view .qx{cursor:%s 7 8, text}\n"
        % (uri(ARROW), uri(ARROW), uri(BEAM))
    )
    print('  arrow  %d bytes' % len(uri(ARROW)))
    print('  beam   %d bytes' % len(uri(BEAM)))
    print('  css    %d bytes' % len(css))
    if '--write' in sys.argv:
        io.open(OUT, 'w', encoding='utf-8', newline='').write(css)
        print('  wrote src/shell/cursor.css')
    else:
        print('  (dry run)')
    return 0


if __name__ == '__main__':
    sys.exit(main())
