# -*- coding: utf-8 -*-
"""Compare the copy in index.html and m/index.html, and report only what is really a decision.

The first version of this tool counted every unmatched text block and reported 52 decisions
across the seven documents. That number was wrong, and wrong in the direction that causes
wasted work: it counted three things as losses that are not losses at all.

  COUNTERS    both pages animate their figures. One capture freezes at `0M+`, the other at
              `9M+`. Five of xtix's nine differences were this.
  LABELS      panel letters, tick marks, `(S)` from a split-letter animation.
  REWRITES    `Prioritised Global expansion` became `Prioritized global expansion`. A diff
              shows that as one deletion and one addition; it is a spelling fix.

So a block from the root is only reported when it has no close relative in the mobile build.
Everything else is noise, and noise in a decision sheet is worse than an empty sheet — it gets
skimmed, and the one real item is skimmed with it.

The threshold is 0.72 on difflib's ratio, which separates `Prioritised Global expansion` /
`Prioritized global expansion` (0.94) from genuinely different claims (below 0.5).
"""
import difflib
import html
import io
import os
import re
import sys

sys.stdout.reconfigure(encoding='utf-8', errors='replace')
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'docs', 'CONTENT_RECONCILIATION.md')
NEAR = 0.72

SECTIONS = ['hero', 'statement', 'philosophy', 'files', 'xtix', 'oasis',
            'eventer', 'medcoin', 'leadership', 'tech', 'final']


def sections_of(path):
    doc = io.open(os.path.join(ROOT, path), encoding='utf-8', errors='replace').read()
    out = {}
    pos = [(m.group(1), m.start()) for m in re.finditer(r'<section[^>]*id="([^"]+)"', doc)]
    for i, (sid, a) in enumerate(pos):
        b = pos[i + 1][1] if i + 1 < len(pos) else len(doc)
        chunk = re.sub(r'<(script|style)[^>]*>.*?</\1>', ' ', doc[a:b], flags=re.S)
        chunk = re.sub(r'<[^>]+>', '\n', chunk)
        blocks = []
        for w in chunk.split('\n'):
            w = re.sub(r'\s+', ' ', html.unescape(w).replace('\xa0', ' ')).strip()
            if w:
                blocks.append(w)
        out[sid] = blocks
    return out


def noise(s):
    """a counter frozen mid-animation, a panel letter, a tick, a split-letter fragment"""
    if len(s.split()) < 3:
        return True
    if re.fullmatch(r'[\d.,%+~–—\-/ ]*[MKB]?\+?', s):
        return True
    return False


def nearest(block, pool):
    best, score = None, 0.0
    for cand in pool:
        r = difflib.SequenceMatcher(None, block.lower(), cand.lower()).ratio()
        if r > score:
            best, score = cand, r
    return best, score


A, B = sections_of('index.html'), sections_of('m/index.html')

rows, body = [], []
tot_real = tot_edit = tot_noise = 0
for sid in SECTIONS:
    ba, bb = A.get(sid, []), B.get(sid, [])
    sa, sb = set(ba), set(bb)
    real, edits, noisy = [], [], 0
    for x in dict.fromkeys(ba):
        if x in sb:
            continue
        if noise(x):
            noisy += 1
            continue
        cand, score = nearest(x, bb)
        if score >= NEAR:
            edits.append((x, cand, score))
        else:
            real.append(x)
    added = [x for x in dict.fromkeys(bb)
             if x not in sa and not noise(x) and nearest(x, ba)[1] < NEAR]
    tot_real += len(real)
    tot_edit += len(edits)
    tot_noise += noisy
    rows.append((sid, len(real), len(added), len(edits), noisy))

    body.append('## `%s`\n' % sid)
    if not real and not added:
        body.append('Nothing to decide. %d rewrites, %d artefacts.\n' % (len(edits), noisy))
    if real:
        body.append('\n**Only in the root, with no close relative in `m/` — DECIDE:**\n')
        for x in real:
            body.append('- [ ] %s' % x)
        body.append('')
    if added:
        body.append('\n**Only in `m/` — new since the root build, keep unless it is wrong:**\n')
        for x in added:
            body.append('- %s' % x)
        body.append('')
    if edits:
        body.append('\n<details><summary>%d rewrites (root → m/), no decision needed</summary>\n'
                    % len(edits))
        for x, y, sc in edits:
            body.append('- `%.2f` %s → **%s**' % (sc, x, y))
        body.append('\n</details>\n')
    body.append('')

head = ['# Content reconciliation — root vs m/', '',
        'Generated by `tools/reconcile_content.py`. Re-run after any copy change.', '',
        'Only the first column is a decision. Rewrites are the same line reworded, and',
        'artefacts are animated counters and panel labels captured at different moments —',
        'neither is lost content, and counting them as such is what produced the earlier',
        'figure of 52.', '',
        '**Real decisions: %d. Rewrites: %d. Artefacts ignored: %d.**'
        % (tot_real, tot_edit, tot_noise), '',
        '| section | decide | new in m/ | rewrites | artefacts |', '|---|---|---|---|---|']
for sid, r, ad, e, nz in rows:
    head.append('| `%s`%s | **%d** | %d | %d | %d |' % (sid, ' ⚠️' if r else '', r, ad, e, nz))
head += ['', '---', '']

io.open(OUT, 'w', encoding='utf-8', newline='').write('\n'.join(head + body))
print('wrote docs/CONTENT_RECONCILIATION.md')
print()
print('%-14s %8s %10s %9s %10s' % ('section', 'DECIDE', 'new in m/', 'rewrites', 'artefacts'))
print('-' * 56)
for sid, r, ad, e, nz in rows:
    print('%-14s %8d %10d %9d %10d %s' % (sid, r, ad, e, nz, '<--' if r else ''))
print('-' * 56)
print('%-14s %8d' % ('TOTAL', tot_real))
